import assert from 'node:assert/strict';
import { test } from 'node:test';
import { buildConcatFile, ffmpegArgs, ffmpegCommand } from '../src/render/video';

const CLIPS = [
  { imagePath: '/p/panels/panel-001.png', durationSec: 2 },
  { imagePath: '/p/panels/panel-002.png', durationSec: 4.25 },
];

test('the concat list holds each still for its own duration', () => {
  const lines = buildConcatFile(CLIPS).trim().split('\n');
  assert.deepEqual(lines, [
    '# generated by VibeToon',
    "file '/p/panels/panel-001.png'",
    'duration 2.000',
    "file '/p/panels/panel-002.png'",
    'duration 4.250',
    // The concat demuxer drops the final entry unless it is repeated.
    "file '/p/panels/panel-002.png'",
  ]);
});

test('quotes in a path cannot break out of the concat entry', () => {
  const escaped = buildConcatFile([{ imagePath: "/p/it's/panel.png", durationSec: 1 }]);
  assert.match(escaped, /file '\/p\/it'\\''s\/panel\.png'/);
});

test('render args scale and pad to the project frame', () => {
  const args = ffmpegArgs({
    concatPath: '/p/concat.txt',
    outPath: '/p/clip.mp4',
    fps: 24,
    width: 1920,
    height: 1080,
  });
  assert.ok(args.includes('-f') && args.includes('concat'));
  assert.equal(args[args.length - 1], '/p/clip.mp4');
  assert.ok(
    args.some((arg) => arg.includes('scale=1920:1080:force_original_aspect_ratio=decrease')),
    'stills keep their aspect ratio inside the frame',
  );
  assert.ok(args.includes('-r') && args[args.indexOf('-r') + 1] === '24');
  assert.ok(!args.includes('-c:a'), 'no audio codec when nothing is wired in');
});

test('an audio track is mixed in and the video stops with it', () => {
  const args = ffmpegArgs({
    concatPath: '/p/concat.txt',
    outPath: '/p/clip.mp4',
    fps: 12,
    width: 640,
    height: 360,
    audioPath: '/p/mix.wav',
  });
  assert.equal(args.filter((arg) => arg === '-i').length, 2);
  assert.ok(args.includes('/p/mix.wav'));
  assert.ok(args.includes('-c:a') && args.includes('-shortest'));
});

test('the printed command quotes anything with a space', () => {
  const command = ffmpegCommand({
    concatPath: '/my projects/concat.txt',
    outPath: '/my projects/clip.mp4',
    fps: 24,
    width: 1920,
    height: 1080,
  });
  assert.match(command, /"\/my projects\/concat\.txt"/);
  assert.match(command, /"\/my projects\/clip\.mp4"/);
});
