import { spawn, spawnSync } from 'node:child_process';
import path from 'node:path';
import { writeFile } from 'node:fs/promises';

let ffmpegChecked = false;
let ffmpegAvailable = false;

/** ffmpeg is optional: everything still works without it, minus the mp4 itself. */
export function hasFfmpeg(): boolean {
  if (!ffmpegChecked) {
    const probe = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' });
    ffmpegAvailable = probe.status === 0;
    ffmpegChecked = true;
  }
  return ffmpegAvailable;
}

export interface VideoClip {
  /** Absolute path to the still image held for this clip. */
  imagePath: string;
  durationSec: number;
}

/**
 * ffmpeg's concat demuxer holds each still for its `duration`, but drops the
 * last one unless it is listed twice, so the final entry is repeated.
 */
export function buildConcatFile(clips: VideoClip[]): string {
  const lines: string[] = ['# generated by VibeToon'];
  for (const clip of clips) {
    lines.push(`file '${clip.imagePath.replace(/'/g, "'\\''")}'`);
    lines.push(`duration ${clip.durationSec.toFixed(3)}`);
  }
  const last = clips[clips.length - 1];
  if (last) lines.push(`file '${last.imagePath.replace(/'/g, "'\\''")}'`);
  return `${lines.join('\n')}\n`;
}

export interface RenderRequest {
  concatPath: string;
  outPath: string;
  fps: number;
  width: number;
  height: number;
  audioPath?: string;
}

export function ffmpegArgs(request: RenderRequest): string[] {
  const scale = `scale=${request.width}:${request.height}:force_original_aspect_ratio=decrease,pad=${request.width}:${request.height}:(ow-iw)/2:(oh-ih)/2:color=black`;
  const args = ['-y', '-f', 'concat', '-safe', '0', '-i', request.concatPath];
  if (request.audioPath) args.push('-i', request.audioPath);
  args.push(
    '-vf',
    scale,
    '-r',
    String(request.fps),
    '-pix_fmt',
    'yuv420p',
    '-c:v',
    'libx264',
    '-preset',
    'veryfast',
    '-crf',
    '20',
  );
  if (request.audioPath) args.push('-c:a', 'aac', '-b:a', '160k', '-shortest');
  args.push(request.outPath);
  return args;
}

export function ffmpegCommand(request: RenderRequest): string {
  return `ffmpeg ${ffmpegArgs(request)
    .map((arg) => (/[\s'"]/.test(arg) ? JSON.stringify(arg) : arg))
    .join(' ')}`;
}

export interface RenderOutcome {
  ok: boolean;
  command: string;
  output: string;
}

/** Run ffmpeg, capturing the tail of its output so a failure is reportable. */
export async function renderVideo(request: RenderRequest): Promise<RenderOutcome> {
  const command = ffmpegCommand(request);
  if (!hasFfmpeg()) {
    return { ok: false, command, output: 'ffmpeg is not installed on this machine.' };
  }

  return new Promise((resolve) => {
    const child = spawn('ffmpeg', ffmpegArgs(request), { stdio: ['ignore', 'pipe', 'pipe'] });
    let buffer = '';
    const capture = (chunk: Buffer) => {
      buffer += chunk.toString();
      if (buffer.length > 8000) buffer = buffer.slice(-8000);
    };
    child.stdout.on('data', capture);
    child.stderr.on('data', capture);
    child.on('error', (error) => resolve({ ok: false, command, output: String(error) }));
    child.on('close', (code) =>
      resolve({ ok: code === 0, command, output: buffer.split('\n').slice(-12).join('\n') }),
    );
  });
}

export async function writeConcatFile(dir: string, clips: VideoClip[]): Promise<string> {
  const concatPath = path.join(dir, 'concat.txt');
  await writeFile(concatPath, buildConcatFile(clips), 'utf8');
  return concatPath;
}
