import type { AlgorithmGuide } from '../guides';
import { BATCH_SELECT_GUIDE } from './batch';
import { CROP_GUIDE, CUTOUT_GUIDE, PALETTE_FILTER_GUIDE, PALETTE_GUIDE, RESIZE_GUIDE, VIDEO_BACKGROUND_GUIDE } from './image';
import { LINES_GUIDE } from './lines';
import { BIND_GUIDE, FACE_GUIDE, PARTS_GUIDE, POSE_GUIDE, RIG_GUIDE } from './rig';
import { STORYBOARD_GUIDE, TIMELINE_GUIDE, WORLD_MAP_GUIDE } from './story';
import { CORPUS_GUIDE, DICTIONARY_GUIDE, GRAMMAR_GUIDE, LEXICON_GUIDE, RANDOM_TEXT_GUIDE } from './text';
import { LINE_GRAPH_GUIDE, VECTORIZE_GUIDE, VECTOR_EDIT_GUIDE } from './vector';
import { ANIMATIC_GUIDE, RIG_MATCH_GUIDE, SHOTS_GUIDE, VIDEO_EDIT_GUIDE, VIDEO_MATCH_GUIDE, VIDEO_SOURCE_GUIDE } from './video';

export const ALGORITHM_GUIDES: readonly AlgorithmGuide[] = [
  LINES_GUIDE,
  CROP_GUIDE, RESIZE_GUIDE, PALETTE_GUIDE, PALETTE_FILTER_GUIDE, CUTOUT_GUIDE, VIDEO_BACKGROUND_GUIDE,
  SHOTS_GUIDE, VIDEO_EDIT_GUIDE, VIDEO_SOURCE_GUIDE, RIG_MATCH_GUIDE, VIDEO_MATCH_GUIDE, ANIMATIC_GUIDE,
  VECTORIZE_GUIDE, VECTOR_EDIT_GUIDE, LINE_GRAPH_GUIDE,
  RIG_GUIDE, BIND_GUIDE, POSE_GUIDE, PARTS_GUIDE, FACE_GUIDE,
  CORPUS_GUIDE, LEXICON_GUIDE, DICTIONARY_GUIDE, GRAMMAR_GUIDE, RANDOM_TEXT_GUIDE,
  TIMELINE_GUIDE, WORLD_MAP_GUIDE, STORYBOARD_GUIDE,
  BATCH_SELECT_GUIDE,
];

export function guideFor(kind: string): AlgorithmGuide | undefined {
  return ALGORITHM_GUIDES.find((guide) => guide.kinds.includes(kind));
}
